version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*